"""
Self-hosts JetBrains Mono instead of loading it from Google Fonts.

    python tools/fetch-fonts.py

Downloads the latin and latin-ext woff2 subsets for the weights the CV
actually uses, into assets/fonts/, and writes assets/css/fonts.css with
local @font-face rules.

Why not just link Google Fonts: the stylesheet is a render-blocking
request to a third party, and it hands every visitor's IP to Google.
Self-hosted, the whole family is ~120 KB served from the same origin.

Re-run this only to change weights or pick up a new version of the font.
"""

import io
import os
import re
import sys
import urllib.request

FAMILY = "JetBrains+Mono:ital,wght@0,400;0,500;0,700;1,400"
SUBSETS = ("latin", "latin-ext")
UA = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
    )
}

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
font_dir = os.path.join(root, "assets", "fonts")
css_out = os.path.join(root, "assets", "css", "fonts.css")


def fetch(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA)).read()


def main():
    api = "https://fonts.googleapis.com/css2?family=%s&display=swap" % FAMILY
    # The API serves woff2 only when it believes the client supports it,
    # hence the browser User-Agent.
    css = fetch(api).decode("utf-8")

    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    if not blocks:
        sys.exit("Could not parse the Google Fonts response.")

    os.makedirs(font_dir, exist_ok=True)

    out = [
        "/* JetBrains Mono, self-hosted.",
        "   Generated by tools/fetch-fonts.py - do not edit by hand.",
        "   SIL Open Font License 1.1, see assets/fonts/OFL.txt */",
        "",
    ]

    for subset, block in blocks:
        if subset not in SUBSETS:
            continue

        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        style = re.search(r"font-style:\s*(\w+)", block).group(1)
        url = re.search(r"url\((https://[^)]+)\)", block).group(1)

        name = "jetbrains-mono-%s%s-%s.woff2" % (
            weight,
            "-italic" if style == "italic" else "",
            subset,
        )
        path = os.path.join(font_dir, name)
        if not os.path.exists(path):
            with open(path, "wb") as f:
                f.write(fetch(url))

        out.append("/* %s */" % subset)
        out.append(block.replace(url, "../fonts/" + name))
        out.append("")
        print("%-44s %4d KB" % (name, os.path.getsize(path) // 1024))

    io.open(css_out, "w", encoding="utf-8").write("\n".join(out))
    print("\nwrote assets/css/fonts.css")


if __name__ == "__main__":
    main()
